# Site settings
title: czers.pl
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Michal Czerski's homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://czers.pl" # the base hostname & protocol for your site
twitter_username: mczers
github_username:  czers

# Build settings
markdown: kramdown
