title = "czers.pl" # Homepage title and page title suffix
baseurl = "http://czers.pl/" # Controls base URL

languageCode = "en-US" # Controls html lang attribute
paginate = 5 # Number of posts to show before paginating
theme = "after-dark" # Uncomment to use as default theme

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "" # Suggested, controls default description meta
  author = "Michał Czerski" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits
  images = [] # Suggested, controls default OpenGraph images
  theme_variant = "solarized-dark" # Optional, for use to overriding default theme

[params.seo.webmaster_verifications]
  google = "Jz4d9KIj3uoXyQJROomPLGP6y7J1XhCVC0ydV9SEwbU" # Optional, Google verification code
  bing = "C168EC3D6381D674B7B69DA95EB32F10" # Optional, Bing verification code
  yandex = "c691d1410e28a4db" # Optional, Yandex verification code
  alexa = "" # Optional, Alexa verification code

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "landing-page"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"

